---

- name: 'Gather facts'
  hosts: 'all'
  gather_facts: true

- name: 'Output the ingress URLs'
  hosts: 'k3s1'
  gather_facts: false
  become: false
  module_defaults:
    kubernetes.core.helm:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s_info:
      kubeconfig: './k3s-kubeconfig'

  tasks:

    - name: 'Output URL nginx-allowed'
      delegate_to: 'localhost'
      ansible.builtin.debug:
        msg:
          "
          You can access the nginx-allowed deployment here:
          http://nginx-allowed.{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}.sslip.io
          "

    - name: 'Output URL nginx-allowed'
      delegate_to: 'localhost'
      ansible.builtin.debug:
        msg:
          "
          You can **NOT** access the nginx-denied deployment here
          (you get 'upstream connect error or disconnect/reset before headers. reset reason: connection timeout'):
          http://nginx-denied.{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}.sslip.io
          "
