---

- name: 'Run playbook-install_k3s.yml'
  ansible.builtin.import_playbook: playbook-install_k3s.yml

- name: 'Run playbook-cilium.yml'
  ansible.builtin.import_playbook: playbook-cilium.yml

- name: 'Run playbook-gateway.yml'
  ansible.builtin.import_playbook: playbook-gateway.yml

- name: 'Run playbook-nginx-allowed.yml'
  ansible.builtin.import_playbook: playbook-nginx-allowed.yml

- name: 'Run playbook-nginx-denied.yml'
  ansible.builtin.import_playbook: playbook-nginx-denied.yml

- name: 'Run playbook-output_urls.yml'
  ansible.builtin.import_playbook: playbook-output_urls.yml
